### consulta de clientes
GET  http://localhost:3000/api/cliente/

### consultar cliente por Id
GET http://localhost:3000/api/cliente/2

### crear clientes
POST http://localhost:3000/api/cliente/
Content-Type: application/json

{
   "nombre":"para borrar",
   "apellido":"borrame",
   "direccion":"CABA -expero",
   "telefono":"1150521454",
   "email":"luis@gmail.com",
   "activo":1,
   "fecha_registro":"2022-12-31" 
}

###editar cliente
PUT http://localhost:3000/api/cliente/2
Content-Type: application/json

{
   "nombre": "Juana",
   "apellido": "Mendez",
   "direccion": "CABA. Argentina",
   "telefono": "1150521454",
   "email": "juana@gmail.com",
   "activo": 1,
   "fecha_registro":"2022-12-31"   
}


### Borrar cliente
DELETE http://localhost:3000/api/cliente/4